DROP TABLE IF EXISTS currency;


CREATE TABLE currency (
                          id SERIAL PRIMARY KEY,
                          code VARCHAR(20) NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          UNIQUE (code)
);

INSERT INTO currency (code, name) VALUES ('AED', 'Dirham dos Emirados');
INSERT INTO currency (code, name) VALUES ('AFN', 'Afghani do Afeganistão');
INSERT INTO currency (code, name) VALUES ('ALL', 'Lek Albanês');
INSERT INTO currency (code, name) VALUES ('AMD', 'Dram Armênio');
INSERT INTO currency (code, name) VALUES ('ANG', 'Guilder das Antilhas');
INSERT INTO currency (code, name) VALUES ('AOA', 'Kwanza Angolano');
INSERT INTO currency (code, name) VALUES ('ARS', 'Peso Argentino');
INSERT INTO currency (code, name) VALUES ('AUD', 'Dólar Australiano');
INSERT INTO currency (code, name) VALUES ('AZN', 'Manat Azeri');
INSERT INTO currency (code, name) VALUES ('BAM', 'Marco Conversível');
INSERT INTO currency (code, name) VALUES ('BBD', 'Dólar de Barbados');
INSERT INTO currency (code, name) VALUES ('BDT', 'Taka de Bangladesh');
INSERT INTO currency (code, name) VALUES ('BGN', 'Lev Búlgaro');
INSERT INTO currency (code, name) VALUES ('BHD', 'Dinar do Bahrein');
INSERT INTO currency (code, name) VALUES ('BIF', 'Franco Burundinense');
INSERT INTO currency (code, name) VALUES ('BND', 'Dólar de Brunei');
INSERT INTO currency (code, name) VALUES ('BOB', 'Boliviano');
INSERT INTO currency (code, name) VALUES ('BRL', 'Real Brasileiro');
INSERT INTO currency (code, name) VALUES ('BRLT', 'Real Brasileiro Turismo');
INSERT INTO currency (code, name) VALUES ('BSD', 'Dólar das Bahamas');
INSERT INTO currency (code, name) VALUES ('BTC', 'Bitcoin');
INSERT INTO currency (code, name) VALUES ('BWP', 'Pula de Botswana');
INSERT INTO currency (code, name) VALUES ('BYN', 'Rublo Bielorrusso');
INSERT INTO currency (code, name) VALUES ('BZD', 'Dólar de Belize');
INSERT INTO currency (code, name) VALUES ('CAD', 'Dólar Canadense');
INSERT INTO currency (code, name) VALUES ('CHF', 'Franco Suíço');
INSERT INTO currency (code, name) VALUES ('CHFRTS', 'Franco Suíço');
INSERT INTO currency (code, name) VALUES ('CLP', 'Peso Chileno');
INSERT INTO currency (code, name) VALUES ('CNH', 'Yuan chinês offshore');
INSERT INTO currency (code, name) VALUES ('CNY', 'Yuan Chinês');
INSERT INTO currency (code, name) VALUES ('COP', 'Peso Colombiano');
INSERT INTO currency (code, name) VALUES ('CRC', 'Colón Costarriquenho');
INSERT INTO currency (code, name) VALUES ('CUP', 'Peso Cubano');
INSERT INTO currency (code, name) VALUES ('CVE', 'Escudo cabo-verdiano');
INSERT INTO currency (code, name) VALUES ('CZK', 'Coroa Checa');
INSERT INTO currency (code, name) VALUES ('DJF', 'Franco do Djubouti');
INSERT INTO currency (code, name) VALUES ('DKK', 'Coroa Dinamarquesa');
INSERT INTO currency (code, name) VALUES ('DOGE', 'Dogecoin');
INSERT INTO currency (code, name) VALUES ('DOP', 'Peso Dominicano');
INSERT INTO currency (code, name) VALUES ('DZD', 'Dinar Argelino');
INSERT INTO currency (code, name) VALUES ('EGP', 'Libra Egípcia');
INSERT INTO currency (code, name) VALUES ('ETB', 'Birr Etíope');
INSERT INTO currency (code, name) VALUES ('ETH', 'Ethereum');
INSERT INTO currency (code, name) VALUES ('EUR', 'Euro');
INSERT INTO currency (code, name) VALUES ('FJD', 'Dólar de Fiji');
INSERT INTO currency (code, name) VALUES ('GBP', 'Libra Esterlina');
INSERT INTO currency (code, name) VALUES ('GEL', 'Lari Georgiano');
INSERT INTO currency (code, name) VALUES ('GHS', 'Cedi Ganês');
INSERT INTO currency (code, name) VALUES ('GMD', 'Dalasi da Gâmbia');
INSERT INTO currency (code, name) VALUES ('GNF', 'Franco de Guiné');
INSERT INTO currency (code, name) VALUES ('GTQ', 'Quetzal Guatemalteco');
INSERT INTO currency (code, name) VALUES ('HKD', 'Dólar de Hong Kong');
INSERT INTO currency (code, name) VALUES ('HNL', 'Lempira Hondurenha');
INSERT INTO currency (code, name) VALUES ('HRK', 'Kuna Croata');
INSERT INTO currency (code, name) VALUES ('HTG', 'Gourde Haitiano');
INSERT INTO currency (code, name) VALUES ('HUF', 'Florim Húngaro');
INSERT INTO currency (code, name) VALUES ('IDR', 'Rupia Indonésia');
INSERT INTO currency (code, name) VALUES ('ILS', 'Novo Shekel Israelense');
INSERT INTO currency (code, name) VALUES ('INR', 'Rúpia Indiana');
INSERT INTO currency (code, name) VALUES ('IQD', 'Dinar Iraquiano');
INSERT INTO currency (code, name) VALUES ('IRR', 'Rial Iraniano');
INSERT INTO currency (code, name) VALUES ('ISK', 'Coroa Islandesa');
INSERT INTO currency (code, name) VALUES ('JMD', 'Dólar Jamaicano');
INSERT INTO currency (code, name) VALUES ('JOD', 'Dinar Jordaniano');
INSERT INTO currency (code, name) VALUES ('JPY', 'Iene Japonês');
INSERT INTO currency (code, name) VALUES ('JPYRTS', 'Iene Japonês');
INSERT INTO currency (code, name) VALUES ('KES', 'Shilling Queniano');
INSERT INTO currency (code, name) VALUES ('KGS', 'Som Quirguistanês');
INSERT INTO currency (code, name) VALUES ('KHR', 'Riel Cambojano');
INSERT INTO currency (code, name) VALUES ('KMF', 'Franco Comorense');
INSERT INTO currency (code, name) VALUES ('KRW', 'Won Sul-Coreano');
INSERT INTO currency (code, name) VALUES ('KWD', 'Dinar Kuwaitiano');
INSERT INTO currency (code, name) VALUES ('KYD', 'Dólar das Ilhas Cayman');
INSERT INTO currency (code, name) VALUES ('KZT', 'Tengue Cazaquistanês');
INSERT INTO currency (code, name) VALUES ('LAK', 'Kip Laosiano');
INSERT INTO currency (code, name) VALUES ('LBP', 'Libra Libanesa');
INSERT INTO currency (code, name) VALUES ('LKR', 'Rúpia de Sri Lanka');
INSERT INTO currency (code, name) VALUES ('LSL', 'Loti do Lesoto');
INSERT INTO currency (code, name) VALUES ('LTC', 'Litecoin');
INSERT INTO currency (code, name) VALUES ('LYD', 'Dinar Líbio');
INSERT INTO currency (code, name) VALUES ('MAD', 'Dirham Marroquino');
INSERT INTO currency (code, name) VALUES ('MDL', 'Leu Moldavo');
INSERT INTO currency (code, name) VALUES ('MGA', 'Ariary Madagascarense');
INSERT INTO currency (code, name) VALUES ('MKD', 'Denar Macedônio');
INSERT INTO currency (code, name) VALUES ('MMK', 'Kyat de Mianmar');
INSERT INTO currency (code, name) VALUES ('MNT', 'Mongolian Tugrik');
INSERT INTO currency (code, name) VALUES ('MOP', 'Pataca de Macau');
INSERT INTO currency (code, name) VALUES ('MRO', 'Ouguiya Mauritana');
INSERT INTO currency (code, name) VALUES ('MUR', 'Rúpia Mauriciana');
INSERT INTO currency (code, name) VALUES ('MVR', 'Rufiyaa Maldiva');
INSERT INTO currency (code, name) VALUES ('MWK', 'Kwacha Malauiana');
INSERT INTO currency (code, name) VALUES ('MXN', 'Peso Mexicano');
INSERT INTO currency (code, name) VALUES ('MYR', 'Ringgit Malaio');
INSERT INTO currency (code, name) VALUES ('MZN', 'Metical de Moçambique');
INSERT INTO currency (code, name) VALUES ('NAD', 'Dólar Namíbio');
INSERT INTO currency (code, name) VALUES ('NGN', 'Naira Nigeriana');
INSERT INTO currency (code, name) VALUES ('NGNI', 'Naira Nigeriana');
INSERT INTO currency (code, name) VALUES ('NGNPARALLEL', 'Naira Nigeriana');
INSERT INTO currency (code, name) VALUES ('NIO', 'Córdoba Nicaraguense');
INSERT INTO currency (code, name) VALUES ('NOK', 'Coroa Norueguesa');
INSERT INTO currency (code, name) VALUES ('NPR', 'Rúpia Nepalesa');
INSERT INTO currency (code, name) VALUES ('NZD', 'Dólar Neozelandês');
INSERT INTO currency (code, name) VALUES ('OMR', 'Rial Omanense');
INSERT INTO currency (code, name) VALUES ('PAB', 'Balboa Panamenho');
INSERT INTO currency (code, name) VALUES ('PEN', 'Sol do Peru');
INSERT INTO currency (code, name) VALUES ('PGK', 'Kina Papua-Nova Guiné');
INSERT INTO currency (code, name) VALUES ('PHP', 'Peso Filipino');
INSERT INTO currency (code, name) VALUES ('PKR', 'Rúpia Paquistanesa');
INSERT INTO currency (code, name) VALUES ('PLN', 'Zlóti Polonês');
INSERT INTO currency (code, name) VALUES ('PYG', 'Guarani Paraguaio');
INSERT INTO currency (code, name) VALUES ('QAR', 'Rial Catarense');
INSERT INTO currency (code, name) VALUES ('RON', 'Leu Romeno');
INSERT INTO currency (code, name) VALUES ('RSD', 'Dinar Sérvio');
INSERT INTO currency (code, name) VALUES ('RUB', 'Rublo Russo');
INSERT INTO currency (code, name) VALUES ('RUBTOD', 'Rublo Russo');
INSERT INTO currency (code, name) VALUES ('RUBTOM', 'Rublo Russo');
INSERT INTO currency (code, name) VALUES ('RWF', 'Franco Ruandês');
INSERT INTO currency (code, name) VALUES ('SAR', 'Riyal Saudita');
INSERT INTO currency (code, name) VALUES ('SCR', 'Rúpias de Seicheles');
INSERT INTO currency (code, name) VALUES ('SDG', 'Libra Sudanesa');
INSERT INTO currency (code, name) VALUES ('SDR', 'DSE');
INSERT INTO currency (code, name) VALUES ('SEK', 'Coroa Sueca');
INSERT INTO currency (code, name) VALUES ('SGD', 'Dólar de Cingapura');
INSERT INTO currency (code, name) VALUES ('SOS', 'Shilling Somaliano');
INSERT INTO currency (code, name) VALUES ('STD', 'Dobra São Tomé/Príncipe');
INSERT INTO currency (code, name) VALUES ('SVC', 'Colon de El Salvador');
INSERT INTO currency (code, name) VALUES ('SYP', 'Libra Síria');
INSERT INTO currency (code, name) VALUES ('SZL', 'Lilangeni Suazilandês');
INSERT INTO currency (code, name) VALUES ('THB', 'Baht Tailandês');
INSERT INTO currency (code, name) VALUES ('TJS', 'Somoni do Tajiquistão');
INSERT INTO currency (code, name) VALUES ('TMT', 'TMT');
INSERT INTO currency (code, name) VALUES ('TND', 'Dinar Tunisiano');
INSERT INTO currency (code, name) VALUES ('TRY', 'Nova Lira Turca');
INSERT INTO currency (code, name) VALUES ('TTD', 'Dólar de Trinidad');
INSERT INTO currency (code, name) VALUES ('TWD', 'Dólar Taiuanês');
INSERT INTO currency (code, name) VALUES ('TZS', 'Shilling Tanzaniano');
INSERT INTO currency (code, name) VALUES ('UAH', 'Hryvinia Ucraniana');
INSERT INTO currency (code, name) VALUES ('UGX', 'Shilling Ugandês');
INSERT INTO currency (code, name) VALUES ('USD', 'Dólar Americano');
INSERT INTO currency (code, name) VALUES ('USDT', 'Dólar Americano');
INSERT INTO currency (code, name) VALUES ('UYU', 'Peso Uruguaio');
INSERT INTO currency (code, name) VALUES ('UZS', 'Som Uzbequistanês');
INSERT INTO currency (code, name) VALUES ('VEF', 'Bolívar Venezuelano');
INSERT INTO currency (code, name) VALUES ('VND', 'Dong Vietnamita');
INSERT INTO currency (code, name) VALUES ('VUV', 'Vatu de Vanuatu');
INSERT INTO currency (code, name) VALUES ('XAF', 'Franco CFA Central');
INSERT INTO currency (code, name) VALUES ('XAGG', 'Prata');
INSERT INTO currency (code, name) VALUES ('XBR', 'Brent Spot');
INSERT INTO currency (code, name) VALUES ('XCD', 'Dólar do Caribe Oriental');
INSERT INTO currency (code, name) VALUES ('XOF', 'Franco CFA Ocidental');
INSERT INTO currency (code, name) VALUES ('XPF', 'Franco CFP');
INSERT INTO currency (code, name) VALUES ('XRP', 'XRP');
INSERT INTO currency (code, name) VALUES ('YER', 'Riyal Iemenita');
INSERT INTO currency (code, name) VALUES ('ZAR', 'Rand Sul-Africano');
INSERT INTO currency (code, name) VALUES ('ZMK', 'Kwacha Zambiana');
INSERT INTO currency (code, name) VALUES ('ZWL', 'Dólar Zimbabuense');
INSERT INTO currency (code, name) VALUES ('XAU', 'Ouro');